Repository accessibility-exchange/platform, pull requests merged in 2022-12, with the labels that each got.

#1373 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/passwords.php
Labels: localization

#1376 feat: add basic text-to-speech (resolves #497)
  package-lock.json
  package.json
  resources/css/_props.css
  resources/css/_tokens.css
  resources/css/base/_base.css
  resources/css/components/_link-list.css
  resources/css/components/_mark.css
  resources/css/components/_tts.css
  resources/css/routes/_welcome.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/fr/passwords.php
  resources/lang/lsq.json
  resources/svg/pause.svg
  resources/svg/play.svg
  resources/svg/stop.svg
  resources/svg/tts.svg
  resources/views/components/expander.blade.php
  resources/views/components/tts/controller.blade.php
  resources/views/components/tts/mark.blade.php
  resources/views/components/tts/orator.blade.php
  resources/views/components/tts/popup.blade.php
  resources/views/layouts/app-medium.blade.php
  resources/views/layouts/app-wide-tabbed.blade.php
  resources/views/layouts/app-wide.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/footer.blade.php
  resources/views/welcome.blade.php
  vite.config.js
Labels: enhancement

#1382 fix: active styling and styles on dark(er) backgrounds appear broken (resolves #1380)
  resources/css/_props.css
  resources/css/_tokens.css
  resources/css/components/_tts.css
Labels: bug

#1391 fix: tts light mode page read wrong focus styling (resolves #1384)
  resources/css/_tokens.css
  resources/css/components/_button.css
Labels: bug

#1374 fix(deploy): changed ordering of artisan commands so that storage is …
  .deploy/accessibility-app/entrypoint.sh
  app/Console/Commands/DeployGlobal.php
  app/Console/Commands/DeployLocal.php
Labels: help wanted

#1395 fix: resolve issue saving Access Needs settings (fixes #1394)
  app/Http/Requests/UpdateAccessNeedsRequest.php
  resources/views/settings/access-needs.blade.php
Labels: bug, blocking

#1396 fix: tts selection not reading back correct text (resolves #1381)
  package-lock.json
  package.json
  resources/css/_tokens.css
  resources/svg/tts.svg
  resources/views/components/tts/orator.blade.php
Labels: bug

#1404 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/passwords.php
Labels: localization

#1407 feat: implement admin color theme, add URL validation to resources editor
  .github/workflows/analyze.yml
  .github/workflows/asset-lint.yml
  .github/workflows/frontend.yml
  .github/workflows/laravel.yml
  app/Filament/Resources/ResourceResource.php
  app/Providers/AppServiceProvider.php
  config/filament.php
  css-props-generator.js
  package-lock.json
  package.json
  resources/css/_tokens.css
  resources/css/filament.css
  resources/views/vendor/filament/components/brand.blade.php
  tailwind.config.js
  vite.config.js
Labels: bug, enhancement

#1409 feat: add page to manage basic website settings
  .github/workflows/laravel.yml
  app/Filament/Resources/InterpretationResource.php
  app/Filament/Resources/InterpretationResource/Pages/ListInterpretations.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/filament-settings.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/dashboard/administrator.blade.php
  resources/views/individuals/partials/about.blade.php
  resources/views/individuals/partials/experiences.blade.php
  resources/views/layouts/footer.blade.php
  resources/views/livewire/admin-estimates-and-agreements.blade.php
  resources/views/livewire/manage-accounts.blade.php
  resources/views/organizations/partials/about.blade.php
  resources/views/projects/partials/overview.blade.php
  resources/views/projects/partials/team.blade.php
  resources/views/regulated-organizations/partials/about.blade.php
  tests/Feature/SettingsTest.php
Labels: enhancement

#1413 ci: resolve a few CI issues
  .github/workflows/frontend.yml
  .github/workflows/lighthouse.yml
  bin/deploy-dev.sh
Labels: bug

#1414 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/passwords.php
Labels: localization

#1441 fix: null value assigned to checkbox (resolves #1440)
  resources/lang/fr/passwords.php
  resources/views/individuals/edit/groups-you-can-connect-to.blade.php
  resources/views/organizations/edit/4.blade.php
  resources/views/projects/edit/2.blade.php
  resources/views/regulated-organizations/edit.blade.php
  resources/views/settings/communication-and-consultation-preferences.blade.php
Labels: bug, blocking
