Repository accessibility-exchange/platform, pull requests merged in 2022-08, with the labels that each got.

#601 chore(localization): update translations
  resources/lang/fr.json
Labels: Localization

#610 fix: ensure that empty nested arrays aren't saved (resolves #506)
  app/Http/Controllers/IndividualController.php
  app/Http/Controllers/OrganizationController.php
  app/Http/Controllers/RegulatedOrganizationController.php
  app/Models/Individual.php
  public/build/assets/app.89783755.css
  public/build/assets/app.d09de753.js
  public/build/manifest.json
  tests/Feature/IndividualTest.php
  tests/Feature/OrganizationTest.php
  tests/RequestFactories/UpdateOrganizationRequestFactory.php
Labels: bug

#621 feat: clean up orphaned CSS
  css-props-generator.js
  package-lock.json
  package.json
  postcss.config.js
  public/build/assets/app.3e8f4488.css
  public/build/assets/app.c860845f.css
  public/build/manifest.json
  resources/css/_tokens.css
  resources/css/app.css
  resources/css/base/_base.css
  resources/css/base/_helpers.css
  resources/css/base/_typography.css
  resources/css/components/_alert.css
  resources/css/components/_auth-card.css
  resources/css/components/_badge.css
  resources/css/components/_brand.css
  resources/css/components/_breadcrumbs.css
  resources/css/components/_button.css
  resources/css/components/_card.css
  resources/css/components/_columns.css
  resources/css/components/_date-input.css
  resources/css/components/_defined-term.css
  resources/css/components/_divider.css
  resources/css/components/_drawer.css
  resources/css/components/_dropdown.css
  resources/css/components/_expander.css
  resources/css/components/_help-bar.css
  resources/css/components/_individual-card.css
  resources/css/components/_input.css
  resources/css/components/_link-list.css
  resources/css/components/_link.css
  resources/css/components/_modal.css
  resources/css/components/_navigation.css
  resources/css/components/_project-card.css
  resources/css/components/_skip-link.css
  resources/css/components/_table.css
  resources/css/components/_tags.css
  resources/css/components/_update.css
  resources/css/compositions/_box.css
  resources/css/compositions/_cover.css
  resources/css/compositions/_grid.css
  resources/css/compositions/_icon.css
  resources/css/compositions/_repel.css
  resources/css/compositions/_sidebar.css
  resources/css/compositions/_switcher.css
  resources/css/layouts/_aside.css
  resources/css/layouts/_banner.css
  resources/css/layouts/_footer.css
  resources/css/layouts/_form.css
  resources/css/layouts/_guest.css
  resources/css/routes/_welcome.css
  resources/css/routes/profiles/_show.css
  resources/css/routes/projects/_manage.css
  resources/css/routes/projects/_show.css
  resources/css/routes/resources/_hub.css
  resources/css/routes/resources/_index.css
  tailwind.config.js
Labels: enhancement

#635 fix: differentiate radio buttons from checkboxes (resolves #634)
  public/build/assets/app.3e8f4488.css
  public/build/assets/app.4f954a8a.css
  public/build/manifest.json
  resources/css/_tokens.css
  resources/css/components/_input.css
Labels: bug

#636 fix: resolve various signup issues
  app/Actions/Fortify/CreateNewUser.php
  app/Http/Controllers/OrganizationController.php
  app/Http/Controllers/RegulatedOrganizationController.php
  app/Http/Requests/SaveUserDetailsRequest.php
  app/Http/Requests/StoreOrganizationRequest.php
  app/Http/Requests/StoreRegulatedOrganizationRequest.php
  app/Models/Invitation.php
  app/Rules/UniqueUserEmail.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/organizations/create.blade.php
  resources/views/organizations/edit/2.blade.php
  resources/views/regulated-organizations/create-initial.blade.php
  resources/views/settings/show.blade.php
  tests/Feature/OrganizationTest.php
  tests/Feature/RegistrationTest.php
Labels: bug

#649 fix: add validation message for phone numbers (fix #639)
  app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateOrganizationContactInformationRequest.php
  app/Http/Requests/UpdateOrganizationRequest.php
  app/Http/Requests/UpdateRegulatedOrganizationRequest.php
  resources/lang/en.json
  resources/lang/en/validation.php
  resources/lang/fr.json
  tests/Feature/RegulatedOrganizationTest.php
  tests/RequestFactories/UpdateRegulatedOrganizationRequestFactory.php
Labels: enhancement

#651 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/validation.php
Labels: localization

#686 ci: changed caching declaration (#662)
  .deploy/accessibility-app/entrypoint.sh
Labels: infrastructure

#692 fix: prevent participants from creating pages (fix #638)
  app/Http/Controllers/IndividualController.php
  app/Policies/IndividualPolicy.php
  app/Traits/HasMultipageEditingAndPublishing.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/dashboard/individual.blade.php
  resources/views/settings/areas-of-interest.blade.php
  routes/individuals.php
  tests/Feature/DashboardTest.php
  tests/Feature/IndividualTest.php
  tests/Feature/RegulatedOrganizationTest.php
  tests/Feature/TranslationTest.php
Labels: bug

#694 fix: persist individual meeting types (fix #643)
  app/Http/Controllers/IndividualController.php
  app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php
Labels: bug

#693 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#695 fix: individual communication and consultation preferences (fix #644)
  resources/views/individuals/partials/communication-and-consultation-preferences.blade.php
  resources/views/individuals/show.blade.php
Labels: bug

#696 fix: success message in notification settings is cut off (fix #664)
  app/View/Components/AppWideTabbedLayout.php
  resources/css/layouts/_banner.css
  resources/views/layouts/app-wide-tabbed.blade.php
  resources/views/settings/notification-list.blade.php
  resources/views/settings/notifications.blade.php
Labels: bug

#698 fix: update success message on save, redirect to published page
  app/Traits/HasMultipageEditingAndPublishing.php
  tests/Feature/IndividualTest.php
  tests/Feature/OrganizationTest.php
  tests/Feature/RegulatedOrganizationTest.php
Labels: enhancement

#699 fix: remove unused links, add contact info and socials
  resources/views/layouts/footer.blade.php
  resources/views/partials/help-bar.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#704 feat: add footer CTA to browse all projects, add CTA to create project
  public/build/assets/app.194aadd7.css
  public/build/assets/app.e94b7979.css
  public/build/manifest.json
  resources/css/_props.css
  resources/css/_tokens.css
  resources/css/components/_link.css
  resources/views/projects/my-projects.blade.php
  resources/views/projects/my-projects/running.blade.php
Labels: enhancement

#707 chore: add seeders for testing (part 1 of 2)
  database/seeders/DevSeeder.php
  resources/views/individuals/partials/experiences.blade.php
Labels: enhancement

#709 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/project.php
Labels: localization

#697 fix: rename language accordions (resolves #669)
  resources/views/components/language-changer.blade.php
  resources/views/components/translation-manager.blade.php
  resources/views/individuals/show.blade.php
  resources/views/organizations/show-language-selection.blade.php
  resources/views/organizations/show.blade.php
  resources/views/regulated-organizations/show-language-selection.blade.php
  resources/views/regulated-organizations/show.blade.php
Labels: bug

#714 ci: create PR with changelog instead of auto-committing
  .github/workflows/update-changelog.yml
  CHANGELOG.md
Labels: documentation

#723 fix: resolve issue with project creation (resolves #717)
  database/seeders/TestDataSeeder.php
  resources/views/projects/edit/1.blade.php
Labels: bug

#735 fix: verify email address changes for individuals (resolves #590)
  app/Actions/Fortify/UpdateUserProfileInformation.php
  app/Http/Controllers/IndividualController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php
  app/Traits/UserEmailVerification.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/edit/communication-and-consultation-preferences.blade.php
  resources/views/partials/flash-messages.blade.php
  resources/views/settings/account-details.blade.php
  resources/views/settings/communication-and-consultation-preferences.blade.php
  resources/views/settings/show.blade.php
  resources/views/users/edit.blade.php
  routes/settings.php
  routes/web.php
  tests/Feature/LocalizationTest.php
  tests/Feature/UserSettingsTest.php
  tests/Feature/UserTest.php
Labels: bug

#745 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#746 fix: clarify language related to leaving organizations (fix #670, fix #676)
  resources/lang/en.json
  resources/lang/en/validation.php
  resources/lang/fr.json
  resources/views/settings/roles-and-permissions.blade.php
Labels: bug

#736 fix: individual user should not be able to access dashboard without selecting a role
  app/Http/Middleware/RedirectForOnboarding.php
  routes/resource-collections.php
  routes/resources.php
  routes/web.php
  tests/Feature/DashboardTest.php
  tests/Feature/IndividualTest.php
Labels: bug

#747 fix: remove duplicate DB_HOST entry in .env.example
  .env.example
Labels: bug

#749 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/validation.php
Labels: localization

#752 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#754 feat: add Flare (resolves #731)
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/logging.php
Labels: help wanted, infrastructure

#756 fix: censor user data in Flare
  config/flare.php
Labels: enhancement, infrastructure

#748 feat: if users enter URLs without a scheme, add it prior to validation
  app/Http/Requests/UpdateIndividualRequest.php
  app/Http/Requests/UpdateOrganizationRequest.php
  app/Http/Requests/UpdateRegulatedOrganizationRequest.php
  app/helpers.php
  tests/Unit/NormalizeUrlHelperTest.php
Labels: enhancement

#758 feat: add columns to users, orgs, and FROs to indicate validation
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2022_07_28_000000_create_organizations_table.php
  database/migrations/2022_07_28_000000_create_regulated_organizations_table.php
Labels: enhancement

#759 fix: remove drop of joinable columns (fix #757)
  database/migrations/2021_03_01_000000_remove_joinable_columns_from_users_table.php
Labels: bug

#769 ci: split deploy commands into deploy:global and deploy:local
  .deploy/accessibility-app/entrypoint.sh
  app/Console/Commands/DeployGlobal.php
  app/Console/Commands/DeployLocal.php
Labels: help wanted, infrastructure

#772 chore(localization): added the Tap into our support network section to the For FRO page
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/about/for-regulated-organizations.blade.php
Labels: enhancement

#779 chore: update text for role types pages (fix #775)
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/about/roles/accessibility-consultants.blade.php
  resources/views/about/roles/community-connectors.blade.php
  resources/views/about/roles/consultation-participants.blade.php
Labels: enhancement

#781 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#785 feat: replace Individual and Organization roles with enums (fix #701)
  app/Enums/IndividualRole.php
  app/Enums/OrganizationRole.php
  app/Http/Controllers/IndividualController.php
  app/Http/Controllers/OrganizationController.php
  app/Http/Middleware/RedirectForOnboarding.php
  app/Http/Requests/SaveIndividualRolesRequest.php
  app/Http/Requests/SaveOrganizationRolesRequest.php
  app/Models/Individual.php
  app/Models/IndividualRole.php
  app/Models/Organization.php
  app/Models/OrganizationRole.php
  database/factories/IndividualFactory.php
  database/factories/OrganizationFactory.php
  database/migrations/2022_07_28_000000_create_individuals_table.php
  database/migrations/2022_07_28_000000_create_organizations_table.php
  database/migrations/2022_07_28_300000_create_individual_roles_table.php
  database/migrations/2022_07_28_300000_create_organization_roles_table.php
  database/migrations/2022_07_28_400000_create_individual_individual_role_table.php
  database/migrations/2022_07_28_400000_create_organization_organization_role_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/DevSeeder.php
  database/seeders/IndividualRoleSeeder.php
  database/seeders/OrganizationRoleSeeder.php
  database/seeders/TestDataSeeder.php
  resources/views/dashboard.blade.php
  resources/views/individuals/index.blade.php
  resources/views/individuals/show-role-edit.blade.php
  resources/views/individuals/show.blade.php
  resources/views/livewire/experiences.blade.php
  resources/views/organizations/index.blade.php
  resources/views/organizations/show-role-edit.blade.php
  resources/views/organizations/show.blade.php
  tests/Feature/DashboardTest.php
  tests/Feature/IndividualRoleTest.php
  tests/Feature/IndividualTest.php
  tests/Feature/OrganizationTest.php
  tests/Feature/ProjectTest.php
  tests/Feature/TranslationTest.php
  tests/Feature/UserSettingsTest.php
Labels: enhancement

#793 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#794 fix: resolve internal server error when removing individual roles (fix #788)
  resources/views/individuals/show-role-edit.blade.php
Labels: bug

#797 fix: hide navigation items for users who shouldn’t have access (fix #789)
  resources/views/components/navigation.blade.php
Labels: bug

#798 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#803 fix: ensure that team trainings component won't throw an error if keys are empty
  resources/views/livewire/team-trainings.blade.php
Labels: bug, blocking

#810 fix: ensure that organization must have role before accessing dashboard
  app/Http/Middleware/RedirectForOnboarding.php
  tests/Feature/DashboardTest.php
Labels: bug

#812 fix: ensure that slugs are always created in both English and French
  app/Models/Organization.php
  app/Models/RegulatedOrganization.php
  app/Models/Resource.php
  app/Models/ResourceCollection.php
  app/Providers/AppServiceProvider.php
  database/factories/ResourceCollectionFactory.php
  database/factories/ResourceFactory.php
  tests/Feature/OrganizationTest.php
  tests/Feature/RegulatedOrganizationTest.php
  tests/Feature/ResourceCollectionTest.php
  tests/Feature/ResourceTest.php
Labels: bug

#814 fix: don’t allow empty language to be added
  resources/views/components/translation-picker.blade.php
Labels: bug

#815 fix: issues with access needs (resolves #783, resolves #784)
  app/Http/Controllers/SettingsController.php
  app/Http/Requests/UpdateAccessNeedsRequest.php
  resources/views/settings/access-needs.blade.php
Labels: bug

#816 fix: save out of date information notification preference (resolves #786)
  app/Http/Requests/UpdateNotificationPreferencesRequest.php
Labels: bug

#820 fix: remove 'find a local community organization' links (resolves #719)
  resources/views/about/roles/accessibility-consultants.blade.php
  resources/views/about/roles/community-connectors.blade.php
  resources/views/about/roles/consultation-participants.blade.php
Labels: bug

#819 fix: prevent users with unverified email from browsing individuals (resolves #640)
  routes/individuals.php
  tests/Feature/IndividualTest.php
Labels: bug

#821 chore: update staging with latest changes
  .github/workflows/deploy-dev.yml
  app/Http/Controllers/SettingsController.php
  app/Http/Middleware/RedirectForOnboarding.php
  app/Http/Requests/UpdateAccessNeedsRequest.php
  app/Http/Requests/UpdateNotificationPreferencesRequest.php
  app/Models/Organization.php
  app/Models/RegulatedOrganization.php
  app/Models/Resource.php
  app/Models/ResourceCollection.php
  app/Providers/AppServiceProvider.php
  database/factories/ResourceCollectionFactory.php
  database/factories/ResourceFactory.php
  resources/lang/fr.json
  resources/views/about/roles/accessibility-consultants.blade.php
  resources/views/about/roles/community-connectors.blade.php
  resources/views/about/roles/consultation-participants.blade.php
  resources/views/components/translation-picker.blade.php
  resources/views/livewire/team-trainings.blade.php
  resources/views/settings/access-needs.blade.php
  routes/individuals.php
  tests/Feature/DashboardTest.php
  tests/Feature/IndividualTest.php
  tests/Feature/OrganizationTest.php
  tests/Feature/RegulatedOrganizationTest.php
  tests/Feature/ResourceCollectionTest.php
  tests/Feature/ResourceTest.php
Labels: enhancement

#830 fix: move language preferences into website section (resolves #684)
  resources/views/settings/show.blade.php
Labels: bug

#831 fix: use active_url validator (resolves #826)
  app/Http/Requests/UpdateIndividualRequest.php
  app/Http/Requests/UpdateOrganizationRequest.php
  app/Http/Requests/UpdateProjectTeamRequest.php
  app/Http/Requests/UpdateRegulatedOrganizationRequest.php
Labels: bug

#844 chore(docs): add instructions for CipherSweet
  README.md
Labels: documentation

#849 fix: enhancedCheckboxes buttons order (resolves #835)
  resources/views/organizations/edit/1.blade.php
  resources/views/projects/edit/1.blade.php
  resources/views/regulated-organizations/edit.blade.php
Labels: bug

#857 chore(docs): add more details for dev setup, add Mailhog instructions
  .env-e
  .env.example
  README.md
Labels: documentation

#859 fix: resolve validation error when creating an update project (fix #858)
  app/Http/Requests/StoreProjectRequest.php
Labels: bug

#861 fix: resolve issue where removing a language removed the wrong language
  resources/views/components/translation-picker.blade.php
Labels: bug

#864 feat: add maintenance mode to dev site
  .github/workflows/deploy-dev.yml
  resources/views/maintenance.blade.php
Labels: enhancement

#846 fix: registration improvements
  app/Actions/Fortify/CreateNewUser.php
  app/Http/Controllers/InvitationController.php
  app/Http/Controllers/UserController.php
  app/Http/Middleware/RedirectForOnboarding.php
  app/Http/Requests/AcceptInvitationRequest.php
  app/Http/Requests/DeclineInvitationRequest.php
  app/Http/Requests/SaveUserLanguagesRequest.php
  app/Http/Requests/StoreInvitationRequest.php
  app/Models/User.php
  app/Observers/UserObserver.php
  app/helpers.php
  database/migrations/2014_10_12_000000_create_users_table.php
  public/build/assets/app.4a002345.css
  public/build/assets/app.880d3ca8.css
  public/build/manifest.json
  resources/css/_tokens.css
  resources/css/app.css
  resources/css/components/_invitation.css
  resources/lang/en/invitation.php
  resources/views/auth/register.blade.php
  resources/views/auth/register/steps/1.blade.php
  resources/views/components/invitation.blade.php
  resources/views/dashboard.blade.php
  resources/views/dashboard/organization.blade.php
  resources/views/dashboard/regulated-organization.blade.php
  resources/views/mail/invitation.blade.php
  resources/views/organizations/show-role-selection.blade.php
  routes/fortify.php
  routes/invitations.php
  tests/Feature/OrganizationTest.php
  tests/Feature/RegistrationTest.php
  tests/Feature/RegulatedOrganizationTest.php
  tests/Feature/UserTest.php
Labels: enhancement

#893 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#886 feat: create and edit generic engagements (towards #615)
  README.md
  app/Enums/EngagementFormat.php
  app/Enums/EngagementRecruitment.php
  app/Http/Controllers/EngagementController.php
  app/Http/Livewire/Contacts.php
  app/Http/Requests/StoreEngagementOutreachRequest.php
  app/Http/Requests/StoreEngagementRecruitmentRequest.php
  app/Http/Requests/StoreEngagementRequest.php
  app/Http/Requests/UpdateEngagementRequest.php
  app/Models/Engagement.php
  database/migrations/2022_07_28_200000_create_engagements_table.php
  public/build/assets/app.0084c667.css
  public/build/assets/app.880d3ca8.css
  public/build/manifest.json
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/engagements/create.blade.php
  resources/views/engagements/edit.blade.php
  resources/views/engagements/manage.blade.php
  resources/views/engagements/show-outreach-selection.blade.php
  resources/views/engagements/show-recruitment-selection.blade.php
  resources/views/livewire/contacts.blade.php
  resources/views/projects/edit/1.blade.php
  resources/views/projects/show-language-selection.blade.php
  routes/engagements.php
  tests/Feature/ContactsTest.php
  tests/Feature/EngagementTest.php
  tests/RequestFactories/StoreEngagementRequestFactory.php
  tests/RequestFactories/UpdateEngagementRequestFactory.php
Labels: enhancement

#898 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#899 fix: undefined array key for experience start year
  resources/views/livewire/experiences.blade.php
Labels: bug

#900 chore(localization): update translations
  resources/lang/fr/invitation.php
Labels: localization

#894 fix: resolves issues with constituency groups
  app/Http/Requests/UpdateOrganizationConstituenciesRequest.php
  app/Models/Individual.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/edit/groups-you-can-connect-to.blade.php
  resources/views/organizations/edit/2.blade.php
  resources/views/organizations/partials/lived-experiences.blade.php
  tests/Feature/IndividualTest.php
Labels: bug

#896 fix: improve languages and language validation
  app/Http/Requests/StoreOrganizationRequest.php
  app/Http/Requests/StoreProjectNameRequest.php
  app/Http/Requests/StoreProjectRequest.php
  app/Http/Requests/StoreRegulatedOrganizationRequest.php
  app/Http/Requests/UpdateOrganizationRequest.php
  app/Http/Requests/UpdateProjectRequest.php
  app/Http/Requests/UpdateRegulatedOrganizationRequest.php
  app/helpers.php
  resources/views/components/translation-picker.blade.php
  tests/Unit/LanguageHelpersTest.php
Labels: bug

#904 feat: add migrations for meetings
  database/migrations/2022_07_28_300000_create_meetings_table.php
Labels: enhancement

#910 fix: remove some more languages
  app/helpers.php
Labels: bug

#903 fix: resolve overlapping logo issue on mobile (resolves #866)
  public/build/assets/app.0084c667.css
  public/build/assets/app.7d09ad33.css
  public/build/manifest.json
  resources/css/components/_help-bar.css
Labels: bug

#902 fix: create and enforce viewAny policies (resolves #789)
  app/Http/Controllers/UserProjectsController.php
  app/Models/Engagement.php
  app/Policies/EngagementPolicy.php
  app/Policies/IndividualPolicy.php
  app/Policies/OrganizationPolicy.php
  app/Policies/ProjectPolicy.php
  app/Policies/RegulatedOrganizationPolicy.php
  app/Providers/AppServiceProvider.php
  app/Statuses/EngagementStatus.php
  database/factories/EngagementFactory.php
  database/migrations/2022_07_28_200000_create_engagements_table.php
  resources/views/components/navigation.blade.php
  routes/engagements.php
  routes/individuals.php
  routes/organizations.php
  routes/projects.php
  routes/regulated-organizations.php
  routes/web.php
  tests/Feature/BlocklistTest.php
  tests/Feature/EngagementTest.php
  tests/Feature/IndividualTest.php
  tests/Feature/ProjectTest.php
Labels: bug

#912 fix: don't show type selection for invitees (resolves #591)
  app/Http/Controllers/UserController.php
  routes/invitations.php
  tests/Feature/UserTest.php
Labels: bug

#915 fix: resolve undefined array key (resolves #913)
  app/Http/Livewire/DatePicker.php
  app/Http/Requests/UpdateProjectTeamRequest.php
  app/Models/Project.php
  app/Models/User.php
  resources/views/engagements/edit.blade.php
  resources/views/individuals/edit/experiences.blade.php
  resources/views/livewire/date-picker.blade.php
  resources/views/livewire/experiences.blade.php
  resources/views/livewire/team-trainings.blade.php
  resources/views/livewire/web-links.blade.php
  resources/views/projects/edit/2.blade.php
  resources/views/regulated-organizations/edit.blade.php
  tests/Feature/ProjectTest.php
Labels: bug

#922 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/forms.php
Labels: localization

#942 chore(localization): update strings in registration page (resolves #792)
  app/Enums/RegulatedOrganizationType.php
  resources/lang/en.json
  resources/lang/en/organization.php
  resources/lang/fr.json
  resources/lang/fr/organization.php
  resources/views/auth/register.blade.php
  resources/views/auth/register/steps/2.blade.php
  resources/views/auth/register/steps/3.blade.php
  resources/views/auth/register/steps/4.blade.php
  resources/views/dashboard.blade.php
  resources/views/organizations/create.blade.php
  resources/views/organizations/show-role-selection.blade.php
  resources/views/organizations/show-type-selection.blade.php
  resources/views/regulated-organizations/create-initial.blade.php
  resources/views/regulated-organizations/show-type-selection.blade.php
Labels: enhancement

#957 fix: resolve issue with setting day to 0 in DatePicker
  app/Http/Livewire/DatePicker.php
  tests/Feature/Http/Livewire/DatePickerTest.php
Labels: bug

#961 fix: restore email templates, exclude vendor views from Prettier
  .prettierignore
  resources/views/vendor/mail/html/button.blade.php
  resources/views/vendor/mail/html/footer.blade.php
  resources/views/vendor/mail/html/header.blade.php
  resources/views/vendor/mail/html/layout.blade.php
  resources/views/vendor/mail/html/message.blade.php
  resources/views/vendor/mail/html/panel.blade.php
  resources/views/vendor/mail/html/subcopy.blade.php
  resources/views/vendor/mail/html/table.blade.php
  resources/views/vendor/mail/text/layout.blade.php
  resources/views/vendor/notifications/email.blade.php
Labels: bug, blocking

#962 fix: restore invitation email formatting
  .prettierignore
  resources/views/mail/invitation.blade.php
Labels: bug, blocking

#974 fix: roles and permissions access (resolves #848)
  app/Http/Controllers/SettingsController.php
  app/Policies/UserPolicy.php
  tests/Feature/UserSettingsTest.php
Labels: bug, blocking

#986 fix: use default working languages when the property is not specified (resolves #865)
  resources/views/individuals/partials/about.blade.php
Labels: bug, blocking
