Repository accessibility-exchange/platform, pull requests merged in 2022-10, with the labels that each got.

#1085 feat: add fields to engagement editor, add meetings creator/editor
  app/Enums/Availability.php
  app/Enums/TimeZone.php
  app/Enums/Weekday.php
  app/Http/Controllers/EngagementController.php
  app/Http/Controllers/MeetingController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Requests/MeetingRequest.php
  app/Http/Requests/UpdateEngagementRequest.php
  app/Models/Engagement.php
  app/Models/Meeting.php
  app/Policies/MeetingPolicy.php
  app/Providers/AuthServiceProvider.php
  app/View/Components/Timespan.php
  app/View/Components/TranslatableInput.php
  app/View/Components/TranslatableTextarea.php
  app/strings.php
  composer.json
  composer.lock
  database/factories/MeetingFactory.php
  database/migrations/2022_09_23_013753_update_engagements_table.php
  database/migrations/2022_09_28_150051_update_meetings_table.php
  resources/css/components/_divider.css
  resources/css/compositions/_box.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/about/for-community-organizations.blade.php
  resources/views/components/card/engagement.blade.php
  resources/views/components/card/organization.blade.php
  resources/views/components/card/regulated-organization.blade.php
  resources/views/components/timespan.blade.php
  resources/views/components/translatable-input.blade.php
  resources/views/components/translatable-textarea.blade.php
  resources/views/engagements/edit.blade.php
  resources/views/engagements/manage.blade.php
  resources/views/engagements/show-criteria-selection.blade.php
  resources/views/individuals/partials/communication-and-consultation-preferences.blade.php
  resources/views/livewire/add-engagement-connector.blade.php
  resources/views/livewire/date-picker.blade.php
  resources/views/livewire/manage-engagement-connector.blade.php
  resources/views/meetings/edit.blade.php
  resources/views/partials/validation-errors.blade.php
  resources/views/regulated-organizations/create-initial.blade.php
  resources/views/resource-collections/show.blade.php
  resources/views/welcome.blade.php
  routes/meetings.php
  routes/web.php
  tests/Datasets/EngagementIsPublishable.php
  tests/Feature/EngagementTest.php
  tests/Feature/Livewire/EstimatesAndAgreementsTest.php
  tests/Feature/MeetingTest.php
  tests/Feature/ResourceCollectionTest.php
  tests/Feature/View/Components/TimespanTest.php
  vite.config.js
Labels: enhancement

#1133 feat: prevent previewing publishable models before they are publishable (resolves #1098)
  app/Http/Controllers/OrganizationController.php
  app/Http/Controllers/RegulatedOrganizationController.php
  app/Models/Individual.php
  app/Policies/IndividualPolicy.php
  app/Policies/OrganizationPolicy.php
  app/Policies/ProjectPolicy.php
  app/Policies/RegulatedOrganizationPolicy.php
  resources/views/individuals/partials/progress.blade.php
  resources/views/organizations/partials/progress.blade.php
  resources/views/projects/partials/progress.blade.php
  resources/views/regulated-organizations/edit.blade.php
  tests/Datasets/IndividualIsPublishable.php
  tests/Feature/BlocklistTest.php
  tests/Feature/IndividualTest.php
  tests/Feature/NotificationListTest.php
  tests/Feature/OrganizationTest.php
  tests/Feature/RegulatedOrganizationTest.php
Labels: bug, blocking

#1137 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1138 fix: method not allowed when editing meetings
  resources/views/meetings/edit.blade.php
Labels: bug, blocking

#1143 feat: custom mysql configuration
  .deploy/accessibility-db/values.yaml
Labels: infrastructure

#1160 fix: validate contact phone/email based on preferred contact method (resolves #1140)
  app/Actions/Fortify/CreateNewUser.php
  app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateOrganizationContactInformationRequest.php
  app/Http/Requests/UpdateProjectTeamRequest.php
  app/Http/Requests/UpdateRegulatedOrganizationRequest.php
  app/Models/Organization.php
  app/Models/Project.php
  app/Models/RegulatedOrganization.php
  app/Traits/ConditionallyRequireContactMethods.php
  resources/lang/en/validation.php
  tests/Datasets/RegulatedOrganizationIsPublishable.php
  tests/Feature/UserSettingsTest.php
Labels: bug, blocking

#1159 fix: properly reflect disability type for organizations when set to specific disabilities
  resources/views/organizations/partials/disability-types.blade.php
Labels: bug, blocking

#1162 chore(localization): update translations
  resources/lang/fr/validation.php
Labels: localization

#1165 fix: resolve logout 419 error for users who've checked 'remember me'
  app/Http/Middleware/VerifyCsrfToken.php
  tests/Feature/AuthenticationTest.php
Labels: bug, blocking

#1167 fix: properly validate specific disability (resolves #1166)
  app/Http/Requests/UpdateOrganizationConstituenciesRequest.php
Labels: bug, blocking

#1170 fix: resolve conflict between Livewire and the expander component (resolves #1149)
  resources/views/components/expander.blade.php
Labels: bug, blocking

#1172 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/organization.php
Labels: localization

#1179 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1153 feat: browse all projects page
  app/Http/Controllers/ProjectController.php
  app/Http/Livewire/AdminEstimatesAndAgreements.php
  app/Http/Livewire/AllProjects.php
  app/Models/Project.php
  database/factories/CriterionFactory.php
  phpstan.neon.dist
  resources/css/app.css
  resources/css/base/_base.css
  resources/css/components/_expander.css
  resources/css/components/_filters.css
  resources/css/layouts/_form.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/components/expander.blade.php
  resources/views/livewire/admin-estimates-and-agreements.blade.php
  resources/views/livewire/all-projects.blade.php
  resources/views/livewire/manage-engagement-connector.blade.php
  resources/views/projects/my-projects.blade.php
  resources/views/projects/show.blade.php
  routes/projects.php
  tests/Feature/Livewire/AllProjectsTest.php
  tests/Feature/Livewire/EstimatesAndAgreementsTest.php
  tests/Feature/ProjectTest.php
Labels: enhancement

#1180 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1186 feat: agree to privacy policy and terms
  app/Actions/Fortify/CreateNewUser.php
  app/Models/User.php
  database/factories/UserFactory.php
  database/migrations/2022_10_18_153227_update_user_privacy_policy_and_terms_of_service.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/about/privacy-policy.blade.php
  resources/views/about/terms-of-service.blade.php
  resources/views/auth/register/steps/4.blade.php
  tests/Feature/IndividualTest.php
  tests/Feature/RegistrationTest.php
Labels: enhancement

#1187 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1192 fix: resolve missing required parameter error (resolves #1177)
  resources/views/engagements/show.blade.php
Labels: bug, blocking

#1193 fix: remove unused media library package (resolves #968)
  app/Http/Livewire/ImageUploader.php
  app/Models/Individual.php
  composer.json
  composer.lock
  resources/lang/en.json
  resources/views/individuals/show.blade.php
  resources/views/livewire/image-uploader.blade.php
Labels: bug

#1190 fix: various bug and style fixes
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/SettingsController.php
  app/Models/Project.php
  config/app.php
  resources/css/components/_badge.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/engagements/manage.blade.php
  resources/views/livewire/manage-engagement-connector.blade.php
  resources/views/partials/flash-messages.blade.php
  resources/views/projects/manage.blade.php
  resources/views/projects/partials/overview.blade.php
  resources/views/projects/partials/project-and-engagements.blade.php
  resources/views/settings/notifications/individual.blade.php
  tests/Feature/MeetingTest.php
Labels: bug

#1205 fix: call to a member function isoFormat() on null (Resolves #1176)
  app/Policies/EngagementPolicy.php
Labels: bug, blocking

#1204 fix: create first project link goes to wrong page (resolves #1201)
  resources/views/dashboard/organization.blade.php
  resources/views/dashboard/regulated-organization.blade.php
Labels: bug

#1202 fix: drop unused media table (follow-up to #1193)
  database/migrations/2022_10_19_161516_drop_media_table.php
  database/schema/mysql-schema.dump
Labels: enhancement

#1206 fix: various engagement QA fixes
  app/Http/Controllers/EngagementController.php
  app/Http/Requests/UpdateAccessNeedsRequest.php
  resources/css/compositions/_icon.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/auth/register/steps/4.blade.php
  resources/views/engagements/manage-participants.blade.php
  resources/views/engagements/manage.blade.php
  tailwind.config.js
Labels: enhancement

#1210 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1209 fix: improvements to card components
  app/Models/Individual.php
  app/Models/Organization.php
  app/Models/RegulatedOrganization.php
  app/Traits/HasDisplayRegion.php
  app/View/Components/Card/Project.php
  resources/css/_props.css
  resources/css/_tokens.css
  resources/css/components/_badge.css
  resources/css/components/_card.css
  resources/css/components/_manage-section.css
  resources/css/themes/_black-brown.css
  resources/css/themes/_black-white.css
  resources/css/themes/_black-yellow.css
  resources/css/themes/_dark.css
  resources/css/themes/_grey-dark.css
  resources/css/themes/_grey-white.css
  resources/css/themes/_light-dark.css
  resources/css/themes/_white-black.css
  resources/css/themes/_yellow-black.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/components/card/engagement.blade.php
  resources/views/components/card/individual.blade.php
  resources/views/components/card/organization.blade.php
  resources/views/components/card/project.blade.php
  resources/views/components/card/regulated-organization.blade.php
  resources/views/components/project-and-engagements.blade.php
  resources/views/dashboard/organization.blade.php
  resources/views/dashboard/partials/notifications.blade.php
  resources/views/dashboard/regulated-organization.blade.php
  resources/views/engagements/manage.blade.php
  resources/views/livewire/all-projects.blade.php
  resources/views/organizations/partials/projects.blade.php
  resources/views/projects/index.blade.php
  resources/views/projects/partials/project-and-contracted-engagements.blade.php
  resources/views/projects/partials/project-and-engagements.blade.php
  resources/views/projects/partials/project-and-participating-engagements.blade.php
  resources/views/regulated-organizations/partials/projects.blade.php
  tests/Feature/EngagementContractorsAndParticipantsTest.php
  tests/Feature/Livewire/AddEngagementConnectorTest.php
  tests/Feature/Livewire/ManageEngagementConnectorTest.php
Labels: enhancement

#1213 fix: system theme dark mode card styles
  resources/css/components/_card.css
  resources/css/themes/_dark.css
Labels: enhancement

#1214 fix: validation messages for groups you can connect to
  app/Http/Requests/UpdateIndividualConstituenciesRequest.php
  app/Http/Requests/UpdateOrganizationConstituenciesRequest.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/edit/groups-you-can-connect-to.blade.php
  resources/views/organizations/edit/2.blade.php
  resources/views/organizations/partials/disability-types.blade.php
  resources/views/organizations/partials/lived-experiences.blade.php
Labels: bug

#1208 fix: update error message for vrs required
  app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateOrganizationContactInformationRequest.php
  app/Http/Requests/UpdateProjectTeamRequest.php
  app/Http/Requests/UpdateRegulatedOrganizationRequest.php
  resources/lang/en.json
  resources/lang/fr.json
  tests/Feature/OrganizationTest.php
  tests/Feature/ProjectTest.php
  tests/Feature/RegulatedOrganizationTest.php
Labels: bug, accessibility and usability

#1215 fix: language messages
  app/Http/Requests/UpdateIndividualConstituenciesRequest.php
  app/Http/Requests/UpdateOrganizationConstituenciesRequest.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/edit/groups-you-can-connect-to.blade.php
  resources/views/organizations/edit/2.blade.php
Labels: enhancement, accessibility and usability

#1217 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/app.php
Labels: localization

#1219 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/auth.php
  resources/lang/fr/consulting-services.php
  resources/lang/fr/forms.php
  resources/lang/fr/individual.php
  resources/lang/fr/invitation.php
  resources/lang/fr/locales.php
  resources/lang/fr/mail.php
  resources/lang/fr/membership.php
  resources/lang/fr/organization.php
  resources/lang/fr/pagination.php
  resources/lang/fr/passwords.php
  resources/lang/fr/project.php
  resources/lang/fr/regulated-organization.php
  resources/lang/fr/resource-collection.php
  resources/lang/fr/resource-select.php
  resources/lang/fr/resource.php
  resources/lang/fr/routes.php
  resources/lang/fr/validation.php
  resources/lang/fr/welcome.php
Labels: localization

#1216 feat: add change request language on show engagements page
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/fr/passwords.php
  resources/views/components/language-changer.blade.php
  resources/views/engagements/show.blade.php
  resources/views/layouts/footer.blade.php
Labels: enhancement

#1218 fix: add required label to required fields
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/engagements/create.blade.php
  resources/views/engagements/edit.blade.php
  resources/views/engagements/show-criteria-selection.blade.php
  resources/views/engagements/show-format-selection.blade.php
  resources/views/engagements/show-recruitment-selection.blade.php
  resources/views/meetings/edit.blade.php
Labels: bug

#1220 fix: remove project team languages (fix #839)
  app/Http/Requests/UpdateProjectTeamRequest.php
  app/Models/Project.php
  database/migrations/2022_07_28_500000_create_all_individual_contracted_projects_view.php
  database/migrations/2022_07_28_500000_create_all_organization_contracted_projects_view.php
  database/migrations/2022_10_24_121706_remove_team_languages_column_from_projects_table.php
  database/schema/mysql-schema.dump
  database/seeders/TestDataSeeder.php
  resources/views/projects/edit/2.blade.php
  resources/views/projects/partials/team.blade.php
  tests/Datasets/ProjectIsPublishable.php
  tests/Feature/IndividualTest.php
  tests/Feature/OrganizationTest.php
  tests/Feature/ProjectTest.php
Labels: enhancement, accessibility and usability

#1221 fix: remove service regions (resolves #727)
  app/Models/Organization.php
  app/Models/RegulatedOrganization.php
  app/helpers.php
  database/factories/OrganizationFactory.php
  database/factories/RegulatedOrganizationFactory.php
  resources/views/organizations/partials/about.blade.php
  resources/views/regulated-organizations/partials/about.blade.php
  tests/Feature/OrganizationTest.php
  tests/Feature/RegulatedOrganizationTest.php
Labels: enhancement, accessibility and usability

#1227 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1230 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1233 chore(localization): update translations
  resources/lang/fr/passwords.php
Labels: localization

#1235 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/passwords.php
Labels: localization

#1238 fix: show icon for password input (resolves #943)
  config/blade-icons.php
  resources/views/components/password-input.blade.php
Labels: enhancement

#1240 fix: display social medias' invalid url error message in-line
  app/Http/Requests/UpdateIndividualRequest.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/edit/about-you.blade.php
Labels: enhancement, accessibility and usability

#1239 feat: add hint for website links
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/edit/about-you.blade.php
Labels: enhancement, accessibility and usability

#1241 fix: add additional require text on required fields
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/engagements/edit.blade.php
Labels: enhancement, accessibility and usability
