Repository accessibility-exchange/platform, pull requests merged in 2022-09, with the labels that each got.

#987 fix: remove db:refresh command from deploy process on staging
  app/Console/Commands/DatabaseRefresh.php
  app/Console/Commands/DeployGlobal.php
Labels: infrastructure

#989 fix: cache icons on deploy (resolves #988)
  .github/workflows/deploy-dev.yml
  app/Console/Commands/DeployLocal.php
Labels: bug, blocking

#997 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/project.php
Labels: localization

#1038 chore: upgrade to Hearth v3, integrate changes
  .gitignore
  .phpstorm.meta.php
  _ide_helper.php
  _ide_helper_models.php
  app/Http/Controllers/ResourceCollectionController.php
  app/Http/Livewire/ResourceSelect.php
  app/Http/Requests/CreateResourceCollectionRequest.php
  app/Http/Requests/DestroyResourceCollectionRequest.php
  app/Http/Requests/UpdateResourceCollectionRequest.php
  app/Policies/ResourceCollectionPolicy.php
  composer.json
  composer.lock
  resources/lang/en/resource-collection.php
  resources/lang/en/resource-select.php
  resources/lang/fr/resource-collection.php
  resources/lang/fr/resource-select.php
  resources/views/livewire/resource-select.blade.php
  resources/views/resource-collections/create.blade.php
  resources/views/resource-collections/edit.blade.php
  resources/views/resource-collections/index.blade.php
  resources/views/resource-collections/show.blade.php
  routes/resource-collections.php
  tests/Feature/AuthenticationTest.php
  tests/Feature/Http/Livewire/LanguagePickerTest.php
  tests/Feature/Http/Livewire/ResourceSelectTest.php
  tests/Feature/Http/Livewire/TeamTrainingsTest.php
  tests/Feature/LanguagePickerTest.php
  tests/Feature/ResourceCollectionTest.php
  tests/Feature/TeamTrainingsTest.php
  tests/Feature/TwoFactorAuthenticationTest.php
Labels: dependencies

#1042 feat: rebuild assets on deploy
  .deploy/accessibility-app/Dockerfile
  .deploy/accessibility-app/entrypoint.sh
  .gitignore
  public/build/assets/app.179b2b4b.js
  public/build/assets/app.d6a959bf.css
  public/build/manifest.json
Labels: infrastructure

#1044 ci: deploy assets to dev environment
  .github/workflows/deploy-dev.yml
Labels: enhancement

#1040 fix: update UpdateIndividualConstituenciesRequest' ethnoracial identity to be optional (resolves #949)
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/edit/groups-you-can-connect-to.blade.php
Labels: bug

#1046 fix: update text for sign language (resolves #976)
  app/Http/Controllers/SettingsController.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/auth/register/steps/1.blade.php
Labels: accessibility and usability

#1047 fix: removed npm build from entrypoint
  .deploy/accessibility-app/entrypoint.sh
Labels: infrastructure

#1049 ci: fix deployment
  .dockerignore
  .github/workflows/deploy-dev.yml
  .github/workflows/refresh-dev.yml
  Dockerfile.cloud
  bin/deploy-dev.sh
  bin/refresh-dev.sh
  docker-compose.cloud.yml
  docker/8.0/Dockerfile
  docker/8.0/php.ini
  docker/8.0/start-container
  docker/8.0/supervisord.conf
  docker/8.1/Dockerfile
  docker/8.2/Dockerfile
  docker/8.2/php.ini
  docker/8.2/start-container
  docker/8.2/supervisord.conf
Labels: infrastructure

#1052 fix: remove italics from field hints (resolve #763)
  resources/css/_props.css
  resources/css/components/_input.css
Labels: bug, accessibility and usability

#1051 chore(localization): updating strings for Project page (resolves #923)
  app/Http/Controllers/EngagementController.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/components/translation-manager.blade.php
  resources/views/components/translation-picker.blade.php
  resources/views/engagements/create.blade.php
  resources/views/engagements/show-criteria-selection.blade.php
  resources/views/engagements/show-language-selection.blade.php
  resources/views/projects/edit/1.blade.php
  resources/views/projects/edit/2.blade.php
  resources/views/projects/partials/team.blade.php
  resources/views/projects/show-language-selection.blade.php
  resources/views/projects/show.blade.php
Labels: enhancement

#1054 chore: add composer localize command
  .github/pull_request_template.md
  composer.json
Labels: enhancement

#1056 fix: undefined array 'current' (resolves #1055)
  resources/views/individuals/partials/experiences.blade.php
Labels: bug, blocking

#1058 chore(localization): updating strings for Settings page (resolves #931)
  app/Enums/EngagementRecruitment.php
  app/Enums/NotificationChannel.php
  app/Enums/TeamRole.php
  app/Http/Controllers/MembershipController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Requests/DestroyUserRequest.php
  app/Models/User.php
  database/seeders/AccessSupportSeeder.php
  resources/css/layouts/_form.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/auth/register/steps/3.blade.php
  resources/views/components/block-modal.blade.php
  resources/views/components/password-input.blade.php
  resources/views/components/remove-member-modal.blade.php
  resources/views/individuals/edit/communication-and-consultation-preferences.blade.php
  resources/views/settings/access-needs.blade.php
  resources/views/settings/account-details.blade.php
  resources/views/settings/areas-of-interest.blade.php
  resources/views/settings/block-list.blade.php
  resources/views/settings/communication-and-consultation-preferences.blade.php
  resources/views/settings/delete-account.blade.php
  resources/views/settings/language-preferences.blade.php
  resources/views/settings/notification-list.blade.php
  resources/views/settings/notifications.blade.php
  resources/views/settings/notifications/individual.blade.php
  resources/views/settings/roles-and-permissions.blade.php
  resources/views/settings/show.blade.php
  tests/Feature/UserTest.php
Labels: enhancement

#1059 chore(localization): update strings in Registration page (resolves #792)
  resources/lang/en.json
  resources/lang/en/passwords.php
  resources/lang/fr.json
  resources/views/auth/forgot-password.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/register/steps/2.blade.php
  resources/views/auth/reset-password.blade.php
  tests/Feature/PasswordResetTest.php
Labels: enhancement

#1065 chore(localization): update strings in Individual Dashboard page
  app/Http/Controllers/IndividualController.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/show-role-edit.blade.php
  resources/views/individuals/show-role-selection.blade.php
  resources/views/organizations/show-role-edit.blade.php
  tests/Feature/IndividualTest.php
Labels: enhancement

#1072 chore(localization): updating strings for Project pages
  app/Traits/HasMultipageEditingAndPublishing.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/components/translation-picker.blade.php
  resources/views/projects/edit.blade.php
  resources/views/projects/edit/1.blade.php
  resources/views/projects/partials/overview.blade.php
Labels: enhancement

#1073 chore: add file with text for future features (Resolves #1053)
  app/strings.php
  config/localizator.php
  phpunit.xml.dist
  resources/lang/en.json
  resources/lang/fr.json
Labels: enhancement

#1078 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1079 fix: enforce password rules in all environments (fix #680, fix #1060)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  app/Providers/AuthServiceProvider.php
  tests/Feature/IndividualTest.php
  tests/Feature/PasswordResetTest.php
  tests/Feature/RegistrationTest.php
  tests/Feature/UserSettingsTest.php
Labels: enhancement

#1077 feat: update strings for error messages (fix #647, fix #659, fix #671, fix #676)
  app/Http/Requests/SaveIndividualRolesRequest.php
  app/Http/Requests/SaveOrganizationRolesRequest.php
  app/Http/Requests/SaveUserContextRequest.php
  app/Http/Requests/SaveUserDetailsRequest.php
  app/Http/Requests/StoreOrganizationRequest.php
  app/Http/Requests/StoreOrganizationTypeRequest.php
  app/Http/Requests/StoreRegulatedOrganizationRequest.php
  app/Http/Requests/StoreRegulatedOrganizationTypeRequest.php
  resources/lang/en.json
  resources/lang/en/passwords.php
  resources/lang/en/validation.php
  resources/lang/fr.json
  tests/Feature/ResourceCollectionTest.php
Labels: enhancement

#1082 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/pagination.php
  resources/lang/fr/passwords.php
  resources/lang/fr/validation.php
Labels: localization

#1081 feat(individual)!: check that page is publishable (Resolves #594)
  app/Models/Individual.php
  resources/views/individuals/partials/progress.blade.php
  tests/Datasets/IndividualIsPublishable.php
  tests/Feature/IndividualTest.php
Labels: enhancement

#1084 fix: fix unique name validation for organization name (resolves #1076)
  app/Http/Requests/StoreOrganizationRequest.php
  app/Http/Requests/StoreRegulatedOrganizationRequest.php
Labels: bug

#1086 chore: remove staging auth
  .deploy/accessibility-app/values.staging.yaml
  public/robots.txt
Labels: infrastructure

#1088 chore(localization): update translations
  resources/lang/fr/resource-collection.php
Labels: localization

#1087 fix: close modal components when outside is clicked and esc is pressed (resolves #1067)
  resources/views/components/block-modal.blade.php
  resources/views/components/remove-member-modal.blade.php
Labels: accessibility and usability

#1091 fix: engagement minimum participants (resolves #1064)
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/engagements/show-criteria-selection.blade.php
Labels: bug

#1090 fix: fix an issue where radio button option was not persisting on errors (resolves #1061)
  resources/views/organizations/partials/disability-types.blade.php
Labels: bug

#1093 chore(localization): update translations
  resources/lang/fr/auth.php
  resources/lang/fr/consulting-services.php
Labels: localization

#1094 feat!: check that org page is publishable (Resolves #595, #829, #1062)
  app/Http/Controllers/OrganizationController.php
  app/Http/Requests/UpdateOrganizationConstituenciesRequest.php
  app/Models/Organization.php
  resources/views/individuals/show.blade.php
  resources/views/organizations/show.blade.php
  resources/views/regulated-organizations/show.blade.php
  routes/organizations.php
  tests/Datasets/IndividualIsPublishable.php
  tests/Datasets/OrganizationIsPublishable.php
  tests/Feature/OrganizationTest.php
Labels: bug, enhancement

#1095 feat!: check that FRO page is publishable (Resolves #596)
  app/Models/RegulatedOrganization.php
  app/Policies/RegulatedOrganizationPolicy.php
  resources/views/regulated-organizations/edit.blade.php
  tests/Datasets/RegulatedOrganizationIsPublishable.php
  tests/Feature/RegulatedOrganizationTest.php
Labels: enhancement

#1099 feat!: check that Project page is publishable (resolves #657, resolves #921)
  app/Http/Requests/UpdateProjectRequest.php
  app/Models/Project.php
  resources/views/projects/edit/1.blade.php
  resources/views/projects/show.blade.php
  tests/Datasets/ProjectIsPublishable.php
  tests/Feature/ProjectTest.php
Labels: enhancement

#1101 fix: required Individual fields aren't validated (resolves #1097)
  app/Http/Controllers/IndividualController.php
  app/Http/Requests/UpdateIndividualExperiencesRequest.php
  app/Http/Requests/UpdateIndividualRequest.php
  resources/lang/en.json
  resources/lang/en/validation.php
  resources/lang/fr.json
  resources/views/individuals/edit/about-you.blade.php
  tests/Feature/IndividualTest.php
Labels: bug

#1100 feat: remove old database notifications (resolves #1080)
  .gitignore
  app/Console/Commands/NotificationsRemoveOld.php
  app/Console/Kernel.php
  docker-compose.yml
Labels: enhancement, infrastructure
