Repository accessibility-exchange/platform, pull requests merged in 2022-11, with the labels that each got.

#1252 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1253 fix: communicate required for translatable fields (Resolves #1155)
  app/View/Components/TranslatableInput.php
  app/View/Components/TranslatableTextarea.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/components/translatable-input.blade.php
  resources/views/components/translatable-textarea.blade.php
  resources/views/engagements/create.blade.php
  resources/views/individuals/edit/about-you.blade.php
  resources/views/individuals/edit/experiences.blade.php
  resources/views/individuals/edit/groups-you-can-connect-to.blade.php
  resources/views/organizations/edit/1.blade.php
  resources/views/organizations/edit/2.blade.php
  resources/views/organizations/partials/disability-types.blade.php
  resources/views/projects/edit/1.blade.php
  resources/views/projects/edit/2.blade.php
  resources/views/regulated-organizations/edit.blade.php
Labels: enhancement

#1255 fix: remove autocomplete (resolves #428)
  package-lock.json
  package.json
  resources/css/_tokens.css
  resources/css/app.css
  resources/css/components/_autocomplete.css
  resources/js/app.js
  resources/js/autocomplete.js
  resources/views/components/translation-manager.blade.php
  resources/views/projects/show-context-selection.blade.php
Labels: enhancement

#1261 fix: undefined constant "skills" (Resolves #1260)
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/edit/experiences.blade.php
Labels: bug

#1262 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/passwords.php
Labels: localization

#1263 fix: type in breadcrumb
  resources/lang/en.json
  resources/views/about/for-community-organizations.blade.php
  resources/views/about/for-individuals.blade.php
  resources/views/about/for-regulated-organizations.blade.php
  resources/views/about/pricing.blade.php
  resources/views/about/privacy-policy.blade.php
  resources/views/about/roles/accessibility-consultant-details.blade.php
  resources/views/about/roles/community-connector-details.blade.php
  resources/views/about/roles/consultation-participant-details.blade.php
  resources/views/about/terms-of-service.blade.php
Labels: bug

#1264 ci(deploy): permissions fix after syncing files to storage
  .deploy/accessibility-app/entrypoint.sh
Labels: infrastructure

#1265 fix: copy changes 221102
  app/Enums/UserContext.php
  app/Models/User.php
  app/Providers/FortifyServiceProvider.php
  config/app.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/auth/register/steps/2.blade.php
  resources/views/resources/index.blade.php
  resources/views/welcome.blade.php
  tests/Feature/ProjectTest.php
  tests/Feature/UserTest.php
Labels: enhancement

#1269 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1273 fix: resolve invalid status check (fixes #1272)
  resources/views/individuals/show.blade.php
Labels: bug, blocking

#1282 fix: resolve various contrast theme bugs (resolves #1277, resolves #1279)
  resources/css/_props.css
  resources/css/components/_alert.css
  resources/css/components/_auth-card.css
  resources/css/components/_badge.css
  resources/css/components/_brand.css
  resources/css/components/_expander.css
  resources/css/components/_input.css
  resources/css/components/_link-list.css
  resources/css/components/_manage-section.css
  resources/css/components/_modal.css
  resources/css/components/_notification.css
  resources/css/compositions/_box.css
  resources/css/routes/_welcome.css
  resources/css/themes/_dark.css
  resources/css/themes/_simple.css
  resources/views/components/auth-card.blade.php
  resources/views/components/notification.blade.php
  resources/views/components/password-input.blade.php
  resources/views/components/theme-preview.blade.php
  resources/views/components/translation-picker.blade.php
  resources/views/dashboard/notifications.blade.php
  resources/views/dashboard/partials/notifications.blade.php
  resources/views/engagements/confirm-access-needs.blade.php
  resources/views/engagements/edit.blade.php
  resources/views/engagements/manage.blade.php
  resources/views/engagements/show-criteria-selection.blade.php
  resources/views/livewire/team-trainings.blade.php
  resources/views/meetings/edit.blade.php
  resources/views/projects/manage.blade.php
  resources/views/projects/my-projects/running.blade.php
Labels: bug, blocking

#1281 fix: remove misleading copy about multiple accounts
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/auth/register/steps/2.blade.php
Labels: accessibility and usability

#1286 fix: add back to top link (resolves #953)
  resources/css/_tokens.css
  resources/css/base/_base.css
  resources/css/routes/_welcome.css
  resources/views/components/back-to-top.blade.php
  resources/views/layouts/app-medium.blade.php
  resources/views/layouts/app-wide-tabbed.blade.php
  resources/views/layouts/app-wide.blade.php
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
Labels: enhancement, accessibility and usability

#1288 fix: ensure errors appear inline, validate experience start/end years, add draft labels
  app/Http/Requests/UpdateEngagementRequest.php
  app/Http/Requests/UpdateIndividualExperiencesRequest.php
  app/Http/Requests/UpdateIndividualRequest.php
  app/Http/Requests/UpdateOrganizationRequest.php
  app/Http/Requests/UpdateProjectRequest.php
  app/Http/Requests/UpdateRegulatedOrganizationRequest.php
  app/Traits/HasMultipageEditingAndPublishing.php
  resources/css/components/_alert.css
  resources/css/components/_button.css
  resources/css/compositions/_repel.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/dashboard/organization.blade.php
  resources/views/dashboard/regulated-organization.blade.php
  resources/views/engagements/edit.blade.php
  resources/views/individuals/edit/about-you.blade.php
  resources/views/individuals/edit/experiences.blade.php
  resources/views/individuals/show.blade.php
  resources/views/organizations/edit/1.blade.php
  resources/views/organizations/show.blade.php
  resources/views/partials/flash-messages.blade.php
  resources/views/projects/edit/1.blade.php
  resources/views/projects/manage.blade.php
  resources/views/projects/show.blade.php
  resources/views/regulated-organizations/edit.blade.php
  resources/views/regulated-organizations/show.blade.php
  tests/Feature/ProjectTest.php
Labels: enhancement, accessibility and usability

#1292 feat: manage access needs (resolves #406, resolves #407, resolves #1130)
  app/Http/Controllers/EngagementController.php
  app/Http/Controllers/SettingsController.php
  app/Models/Engagement.php
  resources/css/_props.css
  resources/css/base/_typography.css
  resources/css/components/_alert.css
  resources/css/layouts/_app.css
  resources/css/themes/_dark.css
  resources/css/themes/_simple.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/engagements/manage-access-needs.blade.php
  resources/views/engagements/manage-participants.blade.php
  resources/views/engagements/show-criteria-selection.blade.php
  resources/views/engagements/show.blade.php
  resources/views/projects/manage.blade.php
  resources/views/settings/access-needs.blade.php
  tests/Feature/EngagementTest.php
  tests/Feature/MeetingTest.php
Labels: bug, enhancement

#1284 feat: display sign language videos in content (Resolves #1268)
  .eslintrc.json
  .prettierrc
  app/Http/Controllers/SettingsController.php
  app/Http/Requests/UpdateWebsiteAccessibilityPreferencesRequest.php
  app/Models/Interpretation.php
  app/View/Components/Interpretation.php
  app/helpers.php
  database/factories/InterpretationFactory.php
  database/migrations/2022_11_02_002440_create_interpretations_table.php
  database/migrations/2022_11_08_181911_change_type_user_sign_language_translations.php
  package-lock.json
  package.json
  resources/css/components/_interpretation.css
  resources/css/routes/_welcome.css
  resources/js/app.js
  resources/js/vimeoPlayer.js
  resources/lang/en.json
  resources/svg/sign-language.svg
  resources/views/about/for-community-organizations.blade.php
  resources/views/about/for-individuals.blade.php
  resources/views/about/for-regulated-organizations.blade.php
  resources/views/about/roles/accessibility-consultants.blade.php
  resources/views/about/roles/community-connectors.blade.php
  resources/views/about/roles/consultation-participants.blade.php
  resources/views/components/interpretation.blade.php
  resources/views/settings/website-accessibility-preferences.blade.php
  resources/views/welcome.blade.php
  tests/Feature/InterpretationTest.php
  tests/Feature/View/Components/InterpretationTest.php
  tests/Unit/LanguageHelpersTest.php
Labels: enhancement, accessibility and usability

#1259 feat: add models and migrations for training modules
  app/Models/Choice.php
  app/Models/Course.php
  app/Models/Module.php
  app/Models/Organization.php
  app/Models/Question.php
  app/Models/Quiz.php
  app/Models/User.php
  database/factories/ChoiceFactory.php
  database/factories/CourseFactory.php
  database/factories/ModuleFactory.php
  database/factories/QuestionFactory.php
  database/factories/QuizFactory.php
  database/migrations/2022_11_01_173407_create_courses_table.php
  database/migrations/2022_11_01_175858_create_modules_table.php
  database/migrations/2022_11_01_175924_create_quizzes_table.php
  database/migrations/2022_11_01_180656_create_questions_table.php
  database/migrations/2022_11_01_195858_create_course_user_table.php
  database/migrations/2022_11_02_045232_create_module_user_table.php
  database/migrations/2022_11_02_045319_create_quiz_user_table.php
  database/migrations/2022_11_10_181232_create_choices_table.php
  database/seeders/ChoiceSeeder.php
  database/seeders/CourseSeeder.php
  database/seeders/ModuleSeeder.php
  database/seeders/QuestionSeeder.php
  database/seeders/QuizSeeder.php
  tests/Feature/ChoiceTest.php
  tests/Feature/CourseTest.php
  tests/Feature/ModuleTest.php
  tests/Feature/OrganizationTest.php
  tests/Feature/QuestionTest.php
  tests/Feature/QuizTest.php
  tests/Feature/UserTest.php
Labels: enhancement

#1300 feat: replace LiveWire datepicker with Alpine Date Input component
  .eslintrc.json
  app/Http/Livewire/DatePicker.php
  app/View/Components/DateInput.php
  package-lock.json
  package.json
  resources/css/_tokens.css
  resources/js/app.js
  resources/js/dateInput.js
  resources/views/components/date-input.blade.php
  resources/views/components/date-picker.blade.php
  resources/views/engagements/edit.blade.php
  resources/views/individuals/edit/about-you.blade.php
  resources/views/livewire/date-picker.blade.php
  resources/views/livewire/team-trainings.blade.php
  resources/views/meetings/edit.blade.php
  resources/views/projects/edit/1.blade.php
  tests/Feature/Livewire/DatePickerTest.php
Labels: bug, blocking

#1308 fix: improve participant selection criteria form handling (resolves #1303, resolves #1304)
  app/Http/Requests/UpdateEngagementSelectionCriteriaRequest.php
  resources/lang/en.json
  resources/lang/fr.json
Labels: bug

#1302 feat: add sign language to language menu (resolves #1256)
  app/Actions/Fortify/CreateNewUser.php
  app/Http/Controllers/SettingsController.php
  app/Http/Requests/UpdateWebsiteAccessibilitySignLanguageTranslationsRequest.php
  app/View/Components/Interpretation.php
  app/View/Components/LanguageSwitcher.php
  config/locales.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/components/language-switcher.blade.php
  resources/views/layouts/banner.blade.php
  routes/settings.php
  tests/Feature/UserSettingsTest.php
  tests/Feature/View/Components/InterpretationTest.php
Labels: enhancement

#1310 chore: update DB schema
  database/schema/mysql-schema.dump
Labels: enhancement

#1314 fix: date picker improvements
  resources/js/app.js
  resources/js/datePicker.js
  resources/views/components/date-picker.blade.php
  resources/views/engagements/edit.blade.php
  resources/views/livewire/team-trainings.blade.php
  resources/views/meetings/edit.blade.php
  resources/views/projects/edit/1.blade.php
Labels: bug

#1315 fix: manage projects layout, copy under publish buttons
  resources/css/components/_badge.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/components/card/engagement.blade.php
  resources/views/engagements/manage.blade.php
  resources/views/individuals/partials/progress.blade.php
  resources/views/organizations/partials/progress.blade.php
  resources/views/projects/manage-estimates-and-agreements.blade.php
  resources/views/projects/manage.blade.php
  resources/views/projects/partials/progress.blade.php
  resources/views/regulated-organizations/edit.blade.php
Labels: bug, accessibility and usability

#1321 fix: interpretation video source fallbacks (resolves #1320)
  app/View/Components/Interpretation.php
  tests/Feature/View/Components/InterpretationTest.php
Labels: bug, blocking

#1325 fix: validation errors for relevant experiences (resolves #1293)
  app/Http/Requests/UpdateIndividualExperiencesRequest.php
Labels: bug, blocking

#1327 fix: add hints for website links (resolves #1274)
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/individuals/edit/about-you.blade.php
  resources/views/livewire/team-trainings.blade.php
  resources/views/organizations/edit/1.blade.php
  resources/views/regulated-organizations/edit.blade.php
Labels: enhancement

#1328 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1330 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1334 fix: prevent accidental erasure of region when editing access needs (fix #1322)
  app/Http/Controllers/SettingsController.php
  tests/Feature/UserSettingsTest.php
Labels: bug, blocking

#1337 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/invitation.php
  resources/lang/fr/locales.php
  resources/lang/fr/passwords.php
Labels: localization

#1340 fix: show draft banner on all draft content (resolves #1299)
  app/Traits/HasMultipageEditingAndPublishing.php
  app/View/Components/Banner.php
  resources/css/layouts/_header.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/fr/locales.php
  resources/lang/fr/passwords.php
  resources/lang/lsq.json
  resources/lang/lsq/invitation.php
  resources/views/components/banner.blade.php
  resources/views/engagements/show.blade.php
  resources/views/individuals/edit/about-you.blade.php
  resources/views/individuals/edit/communication-and-consultation-preferences.blade.php
  resources/views/individuals/edit/experiences.blade.php
  resources/views/individuals/edit/groups-you-can-connect-to.blade.php
  resources/views/individuals/edit/interests.blade.php
  resources/views/individuals/show.blade.php
  resources/views/layouts/app-medium.blade.php
  resources/views/layouts/app-wide-tabbed.blade.php
  resources/views/layouts/app-wide.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/header.blade.php
  resources/views/organizations/edit/1.blade.php
  resources/views/organizations/edit/2.blade.php
  resources/views/organizations/edit/3.blade.php
  resources/views/organizations/edit/4.blade.php
  resources/views/organizations/show.blade.php
  resources/views/projects/edit/1.blade.php
  resources/views/projects/edit/2.blade.php
  resources/views/projects/show.blade.php
  resources/views/regulated-organizations/edit.blade.php
  resources/views/regulated-organizations/show.blade.php
  resources/views/welcome.blade.php
  tests/Feature/View/Components/BannerTest.php
Labels: bug

#1339 fix: standardize contact point display across various pages (fix #1266)
  app/Enums/ContactPerson.php
  app/Http/Controllers/IndividualController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php
  app/Models/Individual.php
  app/Models/Organization.php
  app/Models/Project.php
  app/Models/RegulatedOrganization.php
  app/Models/User.php
  app/Traits/HasContactPerson.php
  app/View/Components/ContactPoint.php
  resources/css/components/_contact-point.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/components/contact-point.blade.php
  resources/views/engagements/leave.blade.php
  resources/views/engagements/manage-participants.blade.php
  resources/views/engagements/show.blade.php
  resources/views/individuals/edit/communication-and-consultation-preferences.blade.php
  resources/views/individuals/partials/communication-and-consultation-preferences.blade.php
  resources/views/organizations/partials/contact-information.blade.php
  resources/views/projects/partials/questions.blade.php
  resources/views/settings/communication-and-consultation-preferences.blade.php
  resources/views/settings/notifications/individual.blade.php
  resources/views/settings/notifications/organization.blade.php
  tests/Feature/EngagementContractorsAndParticipantsTest.php
  tests/Feature/OrganizationTest.php
  tests/Feature/UserTest.php
Labels: bug

#1346 fix: update copies for individual edit page
  resources/lang/en.json
  resources/lang/en/consulting-services.php
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/individuals/edit/about-you.blade.php
  resources/views/individuals/edit/communication-and-consultation-preferences.blade.php
  resources/views/individuals/edit/experiences.blade.php
  resources/views/settings/communication-and-consultation-preferences.blade.php
Labels: accessibility and usability

#1347 fix: can't remove vrs option (resolves #1341)
  app/Http/Controllers/OrganizationController.php
  app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php
  app/Http/Requests/UpdateOrganizationContactInformationRequest.php
  app/Http/Requests/UpdateProjectTeamRequest.php
  app/Http/Requests/UpdateRegulatedOrganizationRequest.php
  tests/Feature/IndividualTest.php
  tests/Feature/OrganizationTest.php
  tests/Feature/ProjectTest.php
  tests/Feature/RegulatedOrganizationTest.php
Labels: bug

#1352 fix: french fields required for individuals (resolves #1349)
  app/Http/Requests/UpdateIndividualRequest.php
  resources/lang/fr/passwords.php
Labels: bug

#1354 fix: restore translatable input and textarea styles (fixes #891)
  resources/css/_tokens.css
  resources/css/components/_expander.css
  resources/views/components/translatable-input.blade.php
  resources/views/components/translatable-textarea.blade.php
Labels: bug

#1355 fix: consulting methods - error message doubled (resolves #1351)
  app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php
  tests/Feature/UserSettingsTest.php
Labels: bug

#1353 fix: resolve mobile layout issues (resolves #1333, resolves #1335)
  resources/css/_tokens.css
  resources/css/base/_base.css
  resources/css/components/_brand.css
  resources/css/components/_help-bar.css
  resources/css/components/_navigation.css
  resources/css/compositions/_sidebar.css
  resources/css/layouts/_app.css
  resources/svg/mark-mono.svg
  resources/svg/mark.svg
  resources/views/components/brand.blade.php
  resources/views/components/navigation.blade.php
  resources/views/partials/help-bar.blade.php
Labels: bug

#1358 fix: don't wrap localization source strings in __()
  resources/lang/en/consulting-services.php
Labels: bug

#1361 chore: copy updates (November 30)
  app/Enums/ConsultingService.php
  resources/lang/en.json
  resources/lang/en/consulting-services.php
  resources/lang/fr.json
  resources/lang/fr/consulting-services.php
  resources/lang/lsq.json
  resources/lang/lsq/consulting-services.php
  resources/views/auth/register/steps/2.blade.php
  resources/views/individuals/edit/about-you.blade.php
  resources/views/individuals/edit/experiences.blade.php
  resources/views/individuals/partials/about.blade.php
  tests/Feature/IndividualTest.php
Labels: enhancement
