Repository accessibility-exchange/platform, pull requests merged in 2023-03, with the labels that each got.

#1575 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1535 fix: separate the projects into different tabs based on users roles (resolves #1469)
  app/Http/Controllers/UserProjectsController.php
  database/seeders/TestDataSeeder.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/dashboard/individual.blade.php
  resources/views/dashboard/organization.blade.php
  resources/views/dashboard/regulated-organization.blade.php
  resources/views/projects/my-projects.blade.php
  tests/Feature/ProjectTest.php
Labels: enhancement

#1587 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1591 chore(localization): update translations
  resources/lang/fr/passwords.php
Labels: localization

#1593 fix: 'Correct answer' on quiz result isn't themed (resolves #1590)
  resources/css/_tokens.css
  resources/css/components/_quiz.css
Labels: bug

#1608 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1610 chore(localization): update translations
  resources/lang/fr/passwords.php
Labels: localization
