Repository accessibility-exchange/platform, pull requests merged in 2023-01, with the labels that each got.

#1461 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/passwords.php
Labels: localization

#1481 fix: select input contrast issue (resolves #1477)
  resources/css/_tokens.css
  resources/css/components/_input.css
Labels: bug

#1484 fix: can change route_has_params in admin panel (resolves #1482)
  app/Filament/Resources/InterpretationResource/Pages/EditInterpretation.php
Labels: bug

#1491 fix: adjust space in between interpreation video and form fields
  resources/views/individuals/edit/about-you.blade.php
  resources/views/individuals/edit/communication-and-consultation-preferences.blade.php
  resources/views/individuals/edit/experiences.blade.php
  resources/views/livewire/experiences.blade.php
Labels: enhancement

#1490 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/passwords.php
Labels: localization

#1496 fix: update link colours (resolves #1494)
  resources/css/_props.css
  resources/css/_tokens.css
  resources/css/themes/_dark.css
Labels: enhancement

#1498 chore(localization): update translations
  resources/lang/fr.json
Labels: localization
