Repository accessibility-exchange/platform, pull requests merged in 2023-02, with the labels that each got.

#1513 fix: copy changes for regulated organization creation
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/regulated-organizations/create-initial.blade.php
  resources/views/regulated-organizations/show-type-selection.blade.php
Labels: enhancement

#1516 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1523 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1525 feat: add sign language icon to languages dropdown (resolves #1524)
  resources/css/_tokens.css
  resources/css/components/_navigation.css
  resources/svg/language.svg
  resources/svg/sign-language.svg
  resources/views/components/language-switcher.blade.php
Labels: enhancement

#1514 feat: add orientation sign up links (resolves #1212)
  app/helpers.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/dashboard/individual.blade.php
  resources/views/dashboard/organization.blade.php
  resources/views/dashboard/regulated-organization.blade.php
  resources/views/individuals/partials/progress.blade.php
  resources/views/organizations/partials/progress.blade.php
  resources/views/projects/partials/progress.blade.php
  resources/views/regulated-organizations/edit.blade.php
  tests/Unit/OrientationLinkHelperTest.php
Labels: enhancement

#1531 feat: add terms of service
  resources/css/_tokens.css
  resources/css/routes/_tos.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/fr/passwords.php
  resources/lang/lsq.json
  resources/views/about/terms-of-service.blade.php
  routes/web.php
Labels: enhancement

#1529 fix: Browse Project Tweaks (resolves #1422)
  resources/css/components/_filters.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/livewire/all-projects.blade.php
  resources/views/projects/partials/progress.blade.php
Labels: enhancement

#1530 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1532 feat: Engagement: If full, show message (resolves #1271)
  app/Policies/EngagementPolicy.php
  resources/css/_tokens.css
  resources/css/components/_link.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/engagements/show.blade.php
Labels: enhancement

#1533 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/passwords.php
Labels: localization

#1556 feat: add HubSpot embed code for chatbox (Resolves #1553)
  resources/views/layouts/app.blade.php
  resources/views/partials/hubspot.blade.php
Labels: enhancement

#1557 fix: newline before the opening <?php (resolves #1552)
  routes/organizations.php
  routes/resources.php
Labels: bug

#1390 feat: training modules views and controllers (resolves #396, #398, #399, #1399)
  app/Http/Controllers/CourseController.php
  app/Http/Controllers/QuizController.php
  app/Http/Livewire/EmailResults.php
  app/Http/Livewire/ModuleContent.php
  app/Http/Requests/StoreQuizResultRequest.php
  app/Mail/QuizResults.php
  app/Models/Choice.php
  app/Models/Course.php
  app/Models/Module.php
  app/Models/Question.php
  app/Models/Quiz.php
  app/Models/User.php
  app/Providers/FortifyServiceProvider.php
  database/factories/ChoiceFactory.php
  database/factories/CourseFactory.php
  database/factories/ModuleFactory.php
  database/factories/QuestionFactory.php
  database/migrations/2022_12_08_193312_drop_value_column_from_choices_table.php
  database/migrations/2022_12_21_184920_remove_finished_at_from_course_user_table.php
  database/migrations/2023_01_25_202134_drop_choices_table.php
  database/migrations/2023_01_26_043044_add_choices_and_correct_choices_columns_to_questions_table.php
  database/migrations/2023_01_27_015926_create_question_quiz_table.php
  database/migrations/2023_01_27_025738_remove_quiz_id_from_questions_table.php
  database/migrations/2023_02_06_213028_drop_attempts_column_from_quiz_user_table.php
  database/migrations/2023_02_14_185236_remove_order_column_from_questions_table.php
  database/migrations/2023_02_14_190146_add_order_column_to_quizzes_table.php
  database/migrations/2023_02_14_205104_add_author_column_to_courses_table.php
  database/seeders/ChoiceSeeder.php
  database/seeders/DevSeeder.php
  resources/css/_props.css
  resources/css/components/_banner.css
  resources/css/components/_quiz.css
  resources/css/themes/_simple.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/auth/login.blade.php
  resources/views/components/card/course.blade.php
  resources/views/courses/index.blade.php
  resources/views/courses/show.blade.php
  resources/views/emails/quiz/results.blade.php
  resources/views/livewire/email-results.blade.php
  resources/views/livewire/module-content.blade.php
  resources/views/quizzes/show.blade.php
  routes/courses.php
  routes/modules.php
  routes/quizzes.php
  routes/web.php
  tests/Feature/ChoiceTest.php
  tests/Feature/CourseTest.php
  tests/Feature/Livewire/EmailResultsTest.php
  tests/Feature/Livewire/ModuleContentTest.php
  tests/Feature/ModuleTest.php
  tests/Feature/QuestionTest.php
  tests/Feature/QuizTest.php
  tests/Feature/UserTest.php
Labels: enhancement

#1558 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1559 Feat: training modules dashboard (resolves #400)
  app/Http/Controllers/UserController.php
  resources/css/_tokens.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/lang/lsq.json
  resources/views/courses/show.blade.php
  resources/views/dashboard.blade.php
  resources/views/dashboard/individual.blade.php
  resources/views/dashboard/organization.blade.php
  resources/views/dashboard/regulated-organization.blade.php
  resources/views/dashboard/training-participant.blade.php
  resources/views/dashboard/trainings.blade.php
  resources/views/quizzes/show-result.blade.php
  routes/web.php
  tests/Feature/QuizTest.php
  tests/Feature/UserTest.php
Labels: enhancement

#1562 chore(localization): update translations
  resources/lang/fr.json
Labels: localization
