Repository accessibility-exchange/platform, pull requests merged in 2023-10, with the labels that each got.

#1924 ci: split code coverage upload task from test task (resolves #1921)
  .github/workflows/laravel.yml
  composer.json
  composer.lock
Labels: enhancement, github_actions

#1925 feat: add introduction videos on signup
  app/Models/User.php
  resources/css/_tokens.css
  resources/views/users/show-introduction.blade.php
  tests/Feature/UserTest.php
Labels: enhancement

#1931 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/passwords.php
  resources/lang/fr/validation.php
Labels: localization

#1938 fix: prevent the creation of interpretation resources (resolves #1936)
  app/Filament/Resources/InterpretationResource.php
  app/Models/Interpretation.php
  app/Policies/InterpretationPolicy.php
  app/Providers/AuthServiceProvider.php
  app/View/Components/Interpretation.php
  database/factories/InterpretationFactory.php
  database/schema/mysql-schema.sql
  tests/Feature/InterpretationTest.php
Labels: bug

#1940 chore(localization): update translations
  resources/lang/fr.json
Labels: localization
