Repository accessibility-exchange/platform, pull requests merged in 2023-11, with the labels that each got.

#1967 feat: prevent editing of page titles
  app/Filament/Resources/PageResource/Pages/EditPage.php
Labels: enhancement

#1959 feat: add sitemap and robots (resolves #1388)
  .gitignore
  app/Console/Commands/GenerateRobots.php
  app/Console/Commands/GenerateSitemap.php
  app/Console/Kernel.php
  config/seo.php
  resources/views/robots.blade.php
  resources/views/sitemap.blade.php
  routes/defined-terms.php
  tests/Feature/DefinedTermTest.php
Labels: enhancement

#1982 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#1984 feat: add French support for registration links
  app/Filament/Pages/ManageGeneralSettings.php
  app/Settings/GeneralSettings.php
  app/helpers.php
  database/settings/2023_11_17_145037_remove_registration_links_to_general_settings.php
  database/settings/2023_11_17_150202_readd_registration_links_to_general_settings.php
  resources/views/dashboard/partials/getting-started-individual.blade.php
  resources/views/dashboard/partials/getting-started-organization.blade.php
  tests/Feature/OrientationLinkHelperTest.php
  tests/Feature/SettingsHelperTest.php
  tests/Feature/SettingsTest.php
Labels: enhancement

#1986 fix: update single quotes used in localized text
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/dashboard/getting-started.blade.php
Labels: bug

#2003 fix: disable delete my account button using blade directive
  resources/views/settings/delete-account.blade.php
Labels: bug

#2009 chore(localization): update translations
  resources/lang/fr.json
  resources/lang/fr/validation.php
Labels: localization

#2017 chore(localization): update translations
  resources/lang/fr.json
Labels: localization
