Repository accessibility-exchange/platform, pull requests merged in 2025-05, with the labels that each got.

#2636 feat: fix login route not defined, adopt Laravel >= 11 structure
  .github/workflows/frontend.yml
  .github/workflows/lighthouse.yml
  app/Console/Kernel.php
  app/Exceptions/Handler.php
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/EncryptCookies.php
  app/Http/Middleware/PreventRequestsDuringMaintenance.php
  app/Http/Middleware/TrimStrings.php
  app/Http/Middleware/TrustHosts.php
  app/Http/Middleware/TrustProxies.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  app/Providers/BroadcastServiceProvider.php
  app/Providers/EventServiceProvider.php
  app/Providers/RouteServiceProvider.php
  artisan
  bootstrap/app.php
  bootstrap/providers.php
  composer.json
  composer.lock
  config/app.php
  config/auth.php
  config/broadcasting.php
  config/cors.php
  config/database.php
  config/filament.php
  config/filesystems.php
  config/hashing.php
  config/logging.php
  config/mail.php
  config/queue.php
  config/services.php
  config/session.php
  config/view.php
  routes/api.php
  routes/channels.php
  routes/console.php
  routes/web.php
  tests/Feature/View/Components/InterpretationTest.php
Labels: bug

#2658 chore(docs): update platform dependencies and Laravel Herd instructions
  README.md
Labels: documentation

#2680 chore(localization): update translations
  resources/lang/fr.json
Labels: localization
