Repository accessibility-exchange/platform, pull requests merged in 2025-06, with the labels that each got.

#2706 feat: adjust Browse All Resources page
  resources/css/_tokens.css
  resources/views/livewire/all-resources.blade.php
  resources/views/vendor/livewire/tailwind-custom.blade.php
Labels: bug, enhancement

#2712 fix: resource collections search (resolves #2695)
  app/Livewire/CollectionResources.php
Labels: bug

#2705 feat: allow public access to resources (resolves #2693)
  app/Http/Controllers/CourseController.php
  app/Models/Course.php
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/components/navigation.blade.php
  resources/views/courses/show.blade.php
  routes/courses.php
  routes/resource-collections.php
  routes/resources.php
  tests/Feature/CourseTest.php
  tests/Feature/ResourceCollectionTest.php
  tests/Feature/ResourceTest.php
Labels: enhancement

#2723 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#2749 feat: restructure admin panel links (resolves #2737)
  app/Filament/Pages/ManageGeneralSettings.php
  app/Filament/Resources/AccessSupportResource.php
  app/Filament/Resources/ContentTypeResource.php
  app/Filament/Resources/DocumentResource.php
  app/Filament/Resources/IdentityResource.php
  app/Filament/Resources/ImpactResource.php
  app/Filament/Resources/InterpretationResource.php
  app/Filament/Resources/LanguageResource.php
  app/Filament/Resources/LibraryResource.php
  app/Filament/Resources/PageResource.php
  app/Filament/Resources/PaymentTypeResource.php
  app/Filament/Resources/ResourceCollectionResource.php
  app/Filament/Resources/ResourceResource.php
  app/Filament/Resources/RevisionResource.php
  app/Filament/Resources/SectorResource.php
  app/Filament/Resources/ToolResource.php
  app/Filament/Resources/TopicResource.php
  app/Providers/AppServiceProvider.php
  app/Providers/Filament/AdminPanelProvider.php
  resources/css/_tokens.css
  resources/css/components/_link-list.css
  resources/views/dashboard/administrator.blade.php
Labels: enhancement
