Repository accessibility-exchange/platform, pull requests merged in 2025-08, with the labels that each got.

#2849 chore(deps): used Node 24
  .kube/app/Dockerfile
  .nvmrc
  README.md
  shell.nix
Labels: dependencies

#2876 fix: block invitation of users with membership or wrong context
  app/Http/Requests/StoreInvitationRequest.php
  resources/lang/en.json
  resources/lang/fr.json
  tests/Datasets/StoreInvitationRequestValidationErrors.php
  tests/Feature/InvitationTest.php
Labels: bug

#2881 feat: prefill and prevent editing of UserContext and email
  app/Http/Controllers/UserController.php
  resources/views/auth/register/steps/3.blade.php
Labels: bug

#2883 fix: run blade formatter
  package.json
  resources/views/auth/login.blade.php
  resources/views/components/auth-session-status.blade.php
  resources/views/components/back-to-top.blade.php
  resources/views/components/block-modal.blade.php
  resources/views/components/date-picker.blade.php
  resources/views/components/language-changer.blade.php
  resources/views/components/media-text.blade.php
  resources/views/components/navigation.blade.php
  resources/views/components/password-input.blade.php
  resources/views/components/placeholder.blade.php
  resources/views/components/theme-preview.blade.php
  resources/views/components/translatable-input.blade.php
  resources/views/components/translatable-textarea.blade.php
  resources/views/dashboard.blade.php
  resources/views/dashboard/administrator.blade.php
  resources/views/dashboard/getting-started.blade.php
  resources/views/dashboard/individual.blade.php
  resources/views/dashboard/organization.blade.php
  resources/views/dashboard/regulated-organization.blade.php
  resources/views/engagements/edit.blade.php
  resources/views/engagements/leave.blade.php
  resources/views/engagements/manage-participants.blade.php
  resources/views/engagements/manage.blade.php
  resources/views/engagements/show-criteria-selection.blade.php
  resources/views/engagements/show.blade.php
  resources/views/individuals/show.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/header.blade.php
  resources/views/livewire/all-resources.blade.php
  resources/views/livewire/browse-engagements.blade.php
  resources/views/livewire/collection-resources.blade.php
  resources/views/livewire/library-resources.blade.php
  resources/views/livewire/manage-engagement-connector.blade.php
  resources/views/meetings/edit.blade.php
  resources/views/organizations/create.blade.php
  resources/views/organizations/show.blade.php
  resources/views/partials/head.blade.php
  resources/views/projects/manage-estimates-and-agreements.blade.php
  resources/views/projects/show.blade.php
  resources/views/quizzes/show.blade.php
  resources/views/regulated-organizations/create-initial.blade.php
  resources/views/regulated-organizations/edit.blade.php
  resources/views/regulated-organizations/show.blade.php
  resources/views/settings/access-needs.blade.php
  resources/views/settings/language-preferences.blade.php
  resources/views/settings/show.blade.php
  resources/views/tools/show.blade.php
Labels: bug

#2886 fix: blade formatter directory expansion
  package.json
  resources/views/components/card/course.blade.php
  resources/views/components/card/engagement.blade.php
  resources/views/components/card/index.blade.php
  resources/views/components/card/library.blade.php
  resources/views/components/card/organization.blade.php
  resources/views/components/card/regulated-organization.blade.php
  resources/views/components/card/resource-collection.blade.php
  resources/views/components/card/resource.blade.php
  resources/views/components/card/tool.blade.php
  resources/views/dashboard/partials/getting-started-organization.blade.php
  resources/views/dashboard/partials/getting-started-regulated-organization.blade.php
  resources/views/individuals/edit/about-you.blade.php
  resources/views/individuals/edit/experiences.blade.php
  resources/views/individuals/partials/about.blade.php
  resources/views/individuals/partials/progress.blade.php
  resources/views/organizations/edit/2.blade.php
  resources/views/organizations/edit/4.blade.php
  resources/views/organizations/partials/constituencies.blade.php
  resources/views/organizations/partials/disability-types.blade.php
  resources/views/organizations/partials/lived-experiences.blade.php
  resources/views/organizations/partials/progress.blade.php
  resources/views/projects/edit/2.blade.php
  resources/views/projects/my-projects/running.blade.php
  resources/views/projects/partials/progress.blade.php
  resources/views/projects/partials/project-and-contracted-engagements.blade.php
  resources/views/projects/partials/questions.blade.php
  resources/views/settings/notifications/organization.blade.php
  resources/views/settings/notifications/regulated-organization.blade.php
  resources/views/vendor/hearth-components/alert.blade.php
  resources/views/vendor/hearth-components/locale-select.blade.php
  resources/views/vendor/livewire/tailwind-custom.blade.php
  resources/views/vendor/pagination/tailwind.blade.php
Labels: bug

#2896 chore(deps): upgrade Pest
  composer.json
  composer.lock
Labels: dependencies

#2895 fix: updates for local nix-shell
  .kube/app/Dockerfile
Labels: dependencies

#2914 fix: bump Filament filesize validation
  app/Filament/Resources/DocumentResource/RelationManagers/RevisionsRelationManager.php
  app/Filament/Resources/RevisionResource.php
Labels: bug

#2910 fix: only show language in download button when translations > 1
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/tools/show.blade.php
Labels: enhancement

#2916 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#2891 fix: issue with external users not getting invitation notification (resolves #2890)
  app/Models/User.php
  app/Notifications/IndividualContractorInvited.php
  app/Notifications/ParticipantInvited.php
  app/Observers/UserObserver.php
  tests/Feature/EngagementContractorsAndParticipantsTest.php
  tests/Feature/Livewire/AddEngagementConnectorTest.php
Labels: bug

#2912 feat: add prompt to change roles (resolves #2865)
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/dashboard.blade.php
Labels: enhancement
