Repository accessibility-exchange/platform, pull requests merged in 2025-07, with the labels that each got.

#2747 feat: list and show tools, download revisions
  app/Filament/Resources/DocumentResource/RelationManagers/RevisionsRelationManager.php
  app/Filament/Resources/RevisionResource.php
  app/Filament/Resources/ToolResource.php
  app/Http/Controllers/DownloadController.php
  app/Http/Controllers/PageController.php
  app/Http/Controllers/ToolController.php
  app/Http/Middleware/ConfirmLanguage.php
  app/Models/Tool.php
  app/Policies/ToolPolicy.php
  app/Traits/RendersSafeContent.php
  composer.json
  composer.lock
  config/filesystems.php
  database/migrations/2025_06_09_165844_create_revisions_table.php
  database/migrations/2025_06_23_190924_create_activity_log_table.php
  database/migrations/2025_06_23_190925_add_event_column_to_activity_log_table.php
  database/migrations/2025_06_23_190926_add_batch_uuid_column_to_activity_log_table.php
  resources/css/_props.css
  resources/css/_tokens.css
  resources/css/components/_card.css
  resources/css/components/_dropdown.css
  resources/css/components/_input.css
  resources/css/routes/_welcome.css
  resources/css/routes/resources/_hub.css
  resources/css/themes/_dark.css
  resources/css/themes/_simple.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/about/show-page.blade.php
  resources/views/components/card/tool.blade.php
  resources/views/components/navigation.blade.php
  resources/views/tools/index.blade.php
  resources/views/tools/show.blade.php
  routes/tools.php
  routes/web.php
  tests/Feature/DownloadTest.php
  tests/Feature/ToolTest.php
Labels: enhancement

#2763 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#2773 fix: show projects link for FROs (resolves #2771)
  resources/views/components/navigation.blade.php
Labels: bug

#2759 feat: add prompt about what to do next (resolves #2200)
  app/Console/Commands/MigrateSettingsData.php
  app/Livewire/Prompt.php
  app/Models/Organization.php
  app/Models/RegulatedOrganization.php
  app/Models/User.php
  app/Statuses/OrganizationStatus.php
  app/Statuses/RegulatedOrganizationStatus.php
  app/Statuses/UserStatus.php
  database/migrations/2025_07_02_184517_add_prompts_column_to_users_table.php
  database/migrations/2025_07_07_160012_add_prompts_column_to_organizations_table.php
  database/migrations/2025_07_07_160039_add_prompts_column_to_regulated_organizations_table.php
  resources/css/components/_alert.css
  resources/lang/en.json
  resources/lang/fr.json
  resources/views/dashboard.blade.php
  resources/views/dashboard/getting-started.blade.php
  resources/views/livewire/prompt.blade.php
  tests/Feature/Console/MigrateSettingsDataTest.php
  tests/Feature/DashboardTest.php
  tests/Feature/IndividualTest.php
  tests/Feature/Livewire/PromptTest.php
  tests/Feature/OrganizationTest.php
  tests/Feature/RegulatedOrganizationTest.php
  tests/Feature/UserTest.php
Labels: enhancement

#2787 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#2789 fix: restrict file upload types ( #2761)
  app/Filament/Resources/DocumentResource/RelationManagers/RevisionsRelationManager.php
  app/Filament/Resources/RevisionResource.php
  resources/lang/en.json
  resources/lang/fr.json
Labels: bug

#2799 fix: resolve issue with 403 on home page
  config/pulse.php
Labels: bug

#2800 fix: don't register default Pulse route
  app/Providers/AppServiceProvider.php
  tests/Feature/Filament/ActivityTest.php
Labels: bug

#2801 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#2805 chore(localization): update translations
  resources/lang/fr.json
Labels: localization

#2806 fix: rename migrate-settings-data command to migrate-data
  .kube/app/entrypoint.sh
  README.md
  app/Console/Commands/MigrateData.php
  tests/Feature/Console/MigrateDataTest.php
Labels: enhancement

#2834 chore(deps): update Filament dependencies
  public/css/filament/filament/app.css
  public/js/filament/forms/components/date-time-picker.js
  public/js/filament/tables/components/table.js
Labels: dependencies
